### ISSUE TITLE
vulnerability

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/fine-uploader#1]
looks like other recent forks were also addressing the vuln:

![image](https://user-images.githubusercontent.com/6306961/90732849-37bb3980-e2bb-11ea-846d-653e2fbe02be.png)

**Comment by limonte** [comment]
I checked forks, they aren't really recent and I can't find actual patches for the `Object.prototype` pollution vulnerability in them: 

![image](https://user-images.githubusercontent.com/6059356/90750712-df496380-e2dd-11ea-831f-68e26a915955.png)

Probably I just can't navigate the Network section properly 🤷 

I'll go with the same fix as in https://github.com/jquery/jquery/commit/753d591aea698e57d6db58c9f722cd0808619b1b
